apiVersion: v1
kind: Secret
metadata:
  name: l1-monitoring-secrets
type: Opaque
data:
  postgres-db: cG9zdGdyZXM=        # postgres
  postgres-user: cG9zdGdyZXM=       # postgres
  postgres-password: cG9zdGdyZXM=   # postgres
  clickhouse-user: ZGVmYXVsdA==     # default
  clickhouse-password: 
  ollama-api-key: 
  app-secret-key: bDFtb25pdG9yaW5nc2VjcmV0a2V5  # l1monitoringsecretkey